<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */

trait BSeller_SkyHub_Trait_Integrators
{

    /**
     * @return BSeller_SkyHub_Model_Integrator_Catalog_Product_Attribute
     */
    protected function catalogProductAttributeIntegrator()
    {
        /** @var BSeller_SkyHub_Model_Integrator_Catalog_Product_Attribute $integrator */
        $integrator = Mage::getSingleton('bseller_skyhub/integrator_catalog_product_attribute');
        return $integrator;
    }


    /**
     * @return BSeller_SkyHub_Model_Integrator_Catalog_Product
     */
    protected function catalogProductIntegrator()
    {
        /** @var BSeller_SkyHub_Model_Integrator_Catalog_Product $integrator */
        $integrator = Mage::getSingleton('bseller_skyhub/integrator_catalog_product');
        return $integrator;
    }


    /**
     * @return BSeller_SkyHub_Model_Integrator_Catalog_Category
     */
    protected function catalogCategoryIntegrator()
    {
        /** @var BSeller_SkyHub_Model_Integrator_Catalog_Category $integrator */
        $integrator = Mage::getSingleton('bseller_skyhub/integrator_catalog_category');
        return $integrator;
    }


    /**
     * @return BSeller_SkyHub_Model_Integrator_Sales_Order_Queue
     */
    protected function orderQueueIntegrator()
    {
        return Mage::getSingleton('bseller_skyhub/integrator_sales_order_queue');
    }


    /**
     * @return BSeller_SkyHub_Model_Integrator_Sales_Order
     */
    protected function orderIntegrator()
    {
        return Mage::getSingleton('bseller_skyhub/integrator_sales_order');
    }


    /**
     * @return BSeller_SkyHub_Model_Integrator_Shipment_Plp
     */
    protected function shipmentPlpIntegrator()
    {
        return Mage::getSingleton('bseller_skyhub/integrator_shipment_plp');
    }

    /**
     * @return BSeller_SkyHub_Model_Integrator_Sales_Order_InvoicedXml
     */
    protected function invoicedXmlIntegrator()
    {
        return Mage::getSingleton('bseller_skyhub/integrator_sales_order_invoicedXml');
    }
}
