<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */

trait BSeller_SkyHub_Trait_Transformers
{

    /**
     * @return BSeller_SkyHub_Model_Transformer_Catalog_Product_Attribute
     */
    public function productAttributeTransformer()
    {
        /** @var BSeller_SkyHub_Model_Transformer_Catalog_Product_Attribute $transformer */
        $transformer = Mage::getSingleton('bseller_skyhub/transformer_catalog_product_attribute');
        return $transformer;
    }

    /**
     * @return BSeller_SkyHub_Model_Transformer_Catalog_Product
     */
    public function productTransformer()
    {
        /** @var BSeller_SkyHub_Model_Transformer_Catalog_Product $transformer */
        $transformer = Mage::getSingleton('bseller_skyhub/transformer_catalog_product');
        return $transformer;
    }

    /**
     * @return BSeller_SkyHub_Model_Transformer_Catalog_Category
     */
    public function categoryTransformer()
    {
        /** @var BSeller_SkyHub_Model_Transformer_Catalog_Category $transformer */
        $transformer = Mage::getSingleton('bseller_skyhub/transformer_catalog_category');
        return $transformer;
    }
}
