<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */

abstract class BSeller_SkyHub_Model_Cron_Queue_Sales_Abstract extends BSeller_SkyHub_Model_Cron_Queue_Abstract
{
    
    use BSeller_SkyHub_Trait_Processors;


    /**
     * @param Mage_Cron_Model_Schedule $schedule
     *
     * @return void
     */
    public function create(Mage_Cron_Model_Schedule $schedule)
    {
    }
}
