<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */

$installer = new Mage_Eav_Model_Entity_Setup('core_setup');
$installer->startSetup();

$installer->addAttribute(
    'catalog_product', 'ignore_marketplace', array(
        'group' => 'General',
        'type' => 'int',
        'backend' => '',
        'frontend_input' => '',
        'frontend' => '',
        'label' => 'Ignore Marketplace?',
        'input' => 'boolean', //text, textarea, select, file, image, multiselect
        'class' => '',
        'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL, // Scope can be SCOPE_STORE, SCOPE_GLOBAL or SCOPE_WEBSITE
        'visible' => true,
        'frontend_class' => '',
        'required' => false, // or true
        'user_defined' => true, // or false
        'used_in_product_listing' => '1',
        'default' => '',
        'note' => "Marque SIM para que o produto não seja enviado à Skyhub / Marketplace."
    )
);

$installer->endSetup();