<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */

/**
 * @var BSeller_SkyHub_Model_Resource_Setup $this
 * @var Magento_Db_Adapter_Pdo_Mysql $conn
 */

$this->startSetup();

//dropping wrong index
$tableName = (string)$this->getTable('bseller_skyhub/entity_id');
$keyName = $this->getIdxName($tableName, array('entity_id', 'entity_type'), Varien_Db_Adapter_Interface::INDEX_TYPE_UNIQUE);
$this->getConnection()->dropIndex($tableName, $keyName);

//recreating the index correctly
$this->addIndex(array('entity_id', 'entity_type', 'store_id'), $tableName);

$this->endSetup();
