<?php

/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2020 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Tescaro <tiago.tescaro@b2wdigital.com>
 */

class BSeller_SkyHub_Block_Adminhtml_Sales_Order_Shipment_Marketplace_Field_Channels
    extends Mage_Core_Block_Html_Select
{
    /**
     * Set name
     * @param string $name
     */
    public function setInputName($name)
    {
        $this->setName($name);
        return $this;
    }
}
