<div class="banners2">
	<div class="col-sm-6">
		<a href="{{store url=''}}paris-nouvelle-vague-collection-ring.html">
			<img src="{{skin url='images/banner-4.jpg'}}" alt="" />
			<span class="s-desc">
				<h3>Get up to 20% off</h3>
				<h4>on handmade pins-brooches</h4>
			</span>
		</a>
	</div>
	<div class="col-sm-6">
		<a href="{{store url=''}}agrafe-earrings.html">
			<img src="{{skin url='images/banner-5.jpg'}}" alt="" />
		</a>
	</div>
</div>
