<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */
class BSeller_SkyHub_Model_Observer_Sales_Abstract extends BSeller_SkyHub_Model_Observer_Abstract
{
    
    /**
     * @param string $configStatus
     * @param string $currentStatus
     *
     * @return bool
     */
    protected function statusMatches($configStatus, $currentStatus)
    {
        if ($currentStatus == $configStatus) {
            return true;
        }
        
        return false;
    }
}
