<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */
class BSeller_SkyHub_Block_Adminhtml_Shipment_Plp
    extends BSeller_SkyHub_Block_Adminhtml_Widget_Grid_Container
{

    protected $_controller = 'adminhtml_shipment_plp';


    /**
     * BSeller_SkyHub_Block_Adminhtml_Shipment_Plp constructor.
     */
    public function __construct()
    {
        BSeller_Core_Block_Adminhtml_Widget_Grid_Container::__construct();
        $this->_headerText = $this->__('Pre-post list (PLP) List');
        $this->updateButton('add', 'label', Mage::helper('bseller_skyhub')->__('Add PLP'));
    }
}
