<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */
trait BSeller_SkyHub_Trait_Eav_Option
{
    
    /**
     * @param int|Mage_Eav_Model_Entity_Attribute $attribute
     * @param int                                 $optionId
     * @param int|Mage_Core_Model_Store           $store
     *
     * @return mixed|null
     *
     * @throws Mage_Core_Model_Store_Exception
     */
    protected function extractAttributeOptionValue($attribute, $optionId, $store = null)
    {
        return $this->getEavAttributeOptionResource()->getAttributeOptionText($attribute, $optionId, $store);
    }
    
    
    /**
     * @return BSeller_SkyHub_Model_Resource_Eav_Entity_Attribute_Option
     */
    protected function getEavAttributeOptionResource()
    {
        return Mage::getResourceSingleton('bseller_skyhub/eav_entity_attribute_option');
    }

}
