<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */

class BSeller_SkyHub_Model_Config_Catalog_Product extends BSeller_SkyHub_Model_Config
{

    /**
     * @return array
     */
    public function getSkyHubFixedAttributes()
    {
        if (empty($this->attributes)) {
            $this->attributes = (array)$this->getConfig()->getNode('skyhub/product_attributes')->asArray();
        }

        return (array)$this->attributes;
    }

    /**
     * @return array
     */
    public function getBlacklistedAttributes()
    {
        if (empty($this->blacklist)) {
            $this->blacklist = (array) $this->getConfig()
                ->getNode('skyhub/catalog/product/attributes/blacklist')
                ->asArray();
            $this->blacklist = array_keys($this->blacklist);
        }

        return $this->blacklist;
    }
}