<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  ${MAGENTO_MODULE_NAMESPACE}
 * @package   ${MAGENTO_MODULE_NAMESPACE}_${MAGENTO_MODULE}
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */
require dirname(__FILE__) . '/abstract.php';

class BSeller_SkyHub_Shell_Queue extends BSeller_SkyHub_Shell_Abstract
{
    
    public function run()
    {
        $this->executeCron();
    }
    
    
    protected function executeCron()
    {
        $this->printLine('teste');
    }
}

(new BSeller_SkyHub_Shell_Queue())->run();
