<?php 
$modules = Mage::getConfig()->getNode('modules')->children();
$modulesArray = (array)$modules;
if(isset($modulesArray['Tm_ProductListGallery'])) {
	$gallery_helper = $this->helper('productlistgallery/data'); 
}
?>
<?php $suffix = strtolower($this->getNameInLayout()); ?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<div class="widget widget-catalogsale-products col-sm-3">
		<!--<div class="page-title category-title">
			<h1><?php echo $this->__('Special products') ?></h1>
		</div>-->
			<?php $suffix = $this->getNameInLayout(); ?>
			<ul class="products-grid" id="widget-catalogsale-products-<?php echo $suffix; ?>">
			<?php foreach ($_products->getItems() as $_product): ?>
				<li itemscope itemtype="http://schema.org/product">
					<div class="wrapper-hover">
						<div class="product-image-container">
							<?php $_product = Mage::getModel('catalog/product')->load($_product->getId()); ?>
							<div class="label-product">             
								<?php if($_product->getData('new')){echo '<span class="new">'.$this->__('New').'</span>';  }?>
								<?php if($_product->getData('sale')){echo '<span class="sale">'.$this->__('Sale').'</span>';  }?>
							</div>
							<a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
								<img id="product-collection-image-<?php echo $_productId; ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($gallery_helper->getHomeGridData('image_width'), $gallery_helper->getHomeGridData('image_height')); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" width="<?php echo $gallery_helper->getHomeGridData('image_width'); ?>" height="<?php echo $gallery_helper->getHomeGridData('image_height'); ?>" />
							</a>
						</div>
					<div class="product-info">
							<h2 class="product-name">
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
									<?php echo mb_substr($this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name'),0,15,'UTF-8').'...'; ?>
								</a>
							</h2>
								<?php echo $this->getPriceHtml($_product, true, '-widget-catalogsale-'.$suffix) ?>
						</div>
					</div>
				</li>
			<?php endforeach; ?>
			</ol>
			<script type="text/javascript">decorateList('widget-catalogsale-products-<?php echo $suffix; ?>', 'none-recursive')</script>
</div>
<?php endif; ?>
