<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */

$this->startSetup();

//**********************************************************************************************************************
// Install bseller_skyhub/customer_attributes_mapping data.
//**********************************************************************************************************************
$this->installSkyHubRequiredAttributes('customer');

$this->endSetup();
