<?php

/**
 * BIT Tools Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BitTools
 * @package   BitTools_ModuleName
 *
 * @copyright Copyright (c) 2018 B2W Digital - BIT Tools.
 *
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */
class BSeller_SkyHub_Test_Model_Functional_Product_Mapping extends BSeller_SkyHub_Test_Product_AbstractProduct
{
    public function setUp()
    {
        parent::setUp();
    }

    public function testMapProductAttribute()
    {
        $this->deleteEavAttribute('height');

        //height attribute id
        $id = 10;

        //testing if the module can create and atach automatically an atribute;
        $mapping = $this->createAndMapProductAttribute($id);

        $this->assertNotNull($mapping->getAttributeId());
    }

    public function tearDown()
    {
        //removing the EAV attribute created for testing;
        $this->deleteEavAttribute('height');

        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}