<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */

class BSeller_SkyHub_Model_Cron_Config_Sales_Order_Status extends BSeller_SkyHub_Model_Cron_Config_Abstract
{

    protected $group = 'cron_sales_order_status';
    
    
    /**
     * @return int
     */
    public function queueCreateLimit()
    {
        return (int) $this->getGroupConfig('queue_create_limit');
    }
    
    
    /**
     * @return int
     */
    public function queueExecuteLimit()
    {
        return (int) $this->getGroupConfig('queue_execute_limit');
    }

    public function orderExpirationDays()
    {
        return (int)$this->getGroupConfig('order_expiration');
    }
}
