<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */
class BSeller_SkyHub_Block_Adminhtml_Shipment_Plp_View_Form_Renderer_Order_Grid extends Varien_Data_Form_Element_Abstract
{
    protected $_element;


    /**
     * @return string
     */
    public function getElementHtml()
    {
        return Mage::helper('core')->getLayout()
            ->createBlock('bseller_skyhub/adminhtml_shipment_plp_view_form_order_grid')
            ->toHtml();
    }
}