<?php

/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2020 B2W Digital - BIT Tools.
 *
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */

class BSeller_SkyHub_Model_Source_Order_Marketplaces
{
    const MKT_CODE_EXTRA = 'Extra';

    const MKT_CODE_CASASBAHIA = 'Casas Bahia';

    const MKT_CODE_PONTOFRIO = 'Ponto Frio';

    /**
     * @return array
     */
    public function toOptionArray()
    {
        return [
            ['value' => self::MKT_CODE_EXTRA, 'label' => self::MKT_CODE_EXTRA],
            ['value' => self::MKT_CODE_CASASBAHIA, 'label' => self::MKT_CODE_CASASBAHIA],
            ['value' => self::MKT_CODE_PONTOFRIO, 'label' => self::MKT_CODE_PONTOFRIO]
        ];
    }
}