<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BSeller
 * @package   BSeller_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */
class BSeller_SkyHub_Model_System_Config_Source_Sales_Order_Status_Complete
    extends Mage_Adminhtml_Model_System_Config_Source_Order_Status
{
    
    use BSeller_SkyHub_Trait_Data;
    
    
    protected $_stateStatuses = Mage_Sales_Model_Order::STATE_COMPLETE;
    
    
    /**
     * @return array
     */
    public function toOptionArray()
    {
        $options = parent::toOptionArray();
        
        foreach ($options as $idx => &$option) {
            $option['label'] = $this->__($option['label']);
        }
        
        return $options;
    }
}
