<?php
$_helper          =  Mage::helper('catalogsearch');
$_value           = $_helper->getEscapedQueryText();
$_url             = $this->getAjaxUrl();
?>
<form id="search_mini_form" action="<?php echo $_helper->getResultUrl() ?>" method="get"
    class="searchautocomplete UI-SEARCHAUTOCOMPLETE"
    data-tip="<?php echo $this->__(Mage::getStoreConfig('searchautocomplete/general/tip')) ?>"
    data-url="<?php echo $_url ?>"
    data-minchars="<?php echo Mage::getStoreConfig('searchautocomplete/general/min_chars') ?>"
    data-delay="<?php echo Mage::getStoreConfig('searchautocomplete/general/delay') ?>"
    data-hide-delay="<?php echo Mage::getStoreConfig('searchautocomplete/general/hide_delay') ?>">

    <div class="form-search">
        <label for="search"><?php echo $this->__('Search:') ?></label>

        <?php if ($this->getFilterType()!='none'):?>
            <div class="nav-search-in">
                <span class="category-fake UI-CATEGORY-TEXT"><?php echo $this->__('All') ?></span>
                <span class="nav-down-arrow"></span>
                <select name="<?php echo $this->getVariableName() ?>" class="category UI-CATEGORY">
                    <option value="0"><?php echo $this->__('All') ?></option>
                        <?php $selectedId = $this->getSelectedId();
                            foreach ($this->getDropdownItems() as $itemId=>$itemName): ?>
                                <option value="<?php echo $itemId ?>"<?php echo ($selectedId == $itemId)?'selected':'' ?> >
                                    <?php echo $itemName ?>
                                </option>
                        <?php endforeach;?>
                 </select>
            </div>
        <?php endif;?>

        <input id="search" type="text" autocomplete="off"  name="<?php echo $_helper->getQueryParamName() ?>" value="<?php echo $_helper->getEscapedQueryText() ?>" class="input-text UI-SEARCH UI-NAV-INPUT" maxlength="<?php echo $_helper->getMaxQueryLength();?>" />

        <button type="submit" title="<?php echo $this->__('Search') ?>" class="button search-button"><span><span><?php echo $this->__('Search') ?></span></span></button>

        <div class="searchautocomplete-loader UI-LOADER">
            <div id="g01"></div>
            <div id="g02"></div>
            <div id="g03"></div>
            <div id="g04"></div>
            <div id="g05"></div>
            <div id="g06"></div>
            <div id="g07"></div>
            <div id="g08"></div>
        </div>
        
        <div style="display:none" id="search_autocomplete" class="UI-PLACEHOLDER search-autocomplete searchautocomplete-placeholder"></div>
    </div>
</form>
